# For 1MBq of 90Y,                                          #
# beta_activity      = 1000000 Bq                           #
# positron_activity  = 32 Bq                                #

#######
# Beta decay branch
#######

/gate/source/addSource VS_beta
/gate/source/VS_beta/gps/type Volume
/gate/source/VS_beta/gps/shape Cylinder
/gate/source/VS_beta/gps/radius 2. cm
/gate/source/VS_beta/gps/halfz 1.0 cm
/gate/source/VS_beta/gps/centre 0. 0. 0. cm
/gate/source/VS_beta/setActivity 300. Bq
/gate/source/VS_beta/gps/angtype iso

############################
# Describe source properties
############################

# Half-Life of the Source
/gate/source/VS_beta/setForcedUnstableFlag  true
/gate/source/VS_beta/setForcedHalfLife 230590.8 s

# Distribution of source
/gate/source/VS_beta/gps/angtype iso

###########################################
# Beta decay from 90Y
#
################################################################################
# Set verbosity of gps output (2 = every event)                                #
# This is essential for checking the composition of the source from histograms #
################################################################################
#/gate/source/VS_beta/gps/verbose 2
################################################################################

# Particle and energy Spectrum
/gate/source/VS_beta/gps/particle e-

/gate/source/VS_beta/gps/energytype Arb
/gate/source/VS_beta/gps/histname arb
/gate/source/VS_beta/gps/emin 0.0 MeV
/gate/source/VS_beta/gps/emax 2.275 MeV

/gate/source/VS_beta/gps/histpoint	0		333
/gate/source/VS_beta/gps/histpoint	0.025		346
/gate/source/VS_beta/gps/histpoint	0.05		363
/gate/source/VS_beta/gps/histpoint	0.075		382
/gate/source/VS_beta/gps/histpoint	0.1		401
/gate/source/VS_beta/gps/histpoint	0.125		419
/gate/source/VS_beta/gps/histpoint	0.15		437
/gate/source/VS_beta/gps/histpoint	0.175		454
/gate/source/VS_beta/gps/histpoint	0.2		471
/gate/source/VS_beta/gps/histpoint	0.225		486
/gate/source/VS_beta/gps/histpoint	0.25		500
/gate/source/VS_beta/gps/histpoint	0.275		514
/gate/source/VS_beta/gps/histpoint	0.3		527
/gate/source/VS_beta/gps/histpoint	0.325		538
/gate/source/VS_beta/gps/histpoint	0.35		549
/gate/source/VS_beta/gps/histpoint	0.375		559
/gate/source/VS_beta/gps/histpoint	0.4		569
/gate/source/VS_beta/gps/histpoint	0.425		577
/gate/source/VS_beta/gps/histpoint	0.45		585
/gate/source/VS_beta/gps/histpoint	0.475		592
/gate/source/VS_beta/gps/histpoint	0.5		598
/gate/source/VS_beta/gps/histpoint	0.525		604
/gate/source/VS_beta/gps/histpoint	0.55		609
/gate/source/VS_beta/gps/histpoint	0.575		614
/gate/source/VS_beta/gps/histpoint	0.6		617
/gate/source/VS_beta/gps/histpoint	0.625		620
/gate/source/VS_beta/gps/histpoint	0.65		623
/gate/source/VS_beta/gps/histpoint	0.675		625
/gate/source/VS_beta/gps/histpoint	0.7		627
/gate/source/VS_beta/gps/histpoint	0.725		628
/gate/source/VS_beta/gps/histpoint	0.75		629
/gate/source/VS_beta/gps/histpoint	0.775		629
/gate/source/VS_beta/gps/histpoint	0.8		629
/gate/source/VS_beta/gps/histpoint	0.825		629
/gate/source/VS_beta/gps/histpoint	0.85		628
/gate/source/VS_beta/gps/histpoint	0.875		627
/gate/source/VS_beta/gps/histpoint	0.9		625
/gate/source/VS_beta/gps/histpoint	0.925		623
/gate/source/VS_beta/gps/histpoint	0.95		621
/gate/source/VS_beta/gps/histpoint	0.975		618
/gate/source/VS_beta/gps/histpoint	1		615
/gate/source/VS_beta/gps/histpoint	1.025		612
/gate/source/VS_beta/gps/histpoint	1.05		608
/gate/source/VS_beta/gps/histpoint	1.075		604
/gate/source/VS_beta/gps/histpoint	1.1		599
/gate/source/VS_beta/gps/histpoint	1.125		594
/gate/source/VS_beta/gps/histpoint	1.15		589
/gate/source/VS_beta/gps/histpoint	1.175		583
/gate/source/VS_beta/gps/histpoint	1.2		578
/gate/source/VS_beta/gps/histpoint	1.225		571
/gate/source/VS_beta/gps/histpoint	1.25		564
/gate/source/VS_beta/gps/histpoint	1.275		556
/gate/source/VS_beta/gps/histpoint	1.3		549
/gate/source/VS_beta/gps/histpoint	1.325		540
/gate/source/VS_beta/gps/histpoint	1.35		531
/gate/source/VS_beta/gps/histpoint	1.375		522
/gate/source/VS_beta/gps/histpoint	1.4		512
/gate/source/VS_beta/gps/histpoint	1.425		501
/gate/source/VS_beta/gps/histpoint	1.45		490
/gate/source/VS_beta/gps/histpoint	1.475		479
/gate/source/VS_beta/gps/histpoint	1.5		467
/gate/source/VS_beta/gps/histpoint	1.525		454
/gate/source/VS_beta/gps/histpoint	1.55		441
/gate/source/VS_beta/gps/histpoint	1.575		427
/gate/source/VS_beta/gps/histpoint	1.6		412
/gate/source/VS_beta/gps/histpoint	1.625		397
/gate/source/VS_beta/gps/histpoint	1.65		382
/gate/source/VS_beta/gps/histpoint	1.675		366
/gate/source/VS_beta/gps/histpoint	1.7		349
/gate/source/VS_beta/gps/histpoint	1.725		332
/gate/source/VS_beta/gps/histpoint	1.75		315
/gate/source/VS_beta/gps/histpoint	1.775		297
/gate/source/VS_beta/gps/histpoint	1.8		278
/gate/source/VS_beta/gps/histpoint	1.825		260
/gate/source/VS_beta/gps/histpoint	1.85		241
/gate/source/VS_beta/gps/histpoint	1.875		222
/gate/source/VS_beta/gps/histpoint	1.9		203
/gate/source/VS_beta/gps/histpoint	1.925		184
/gate/source/VS_beta/gps/histpoint	1.95		165
/gate/source/VS_beta/gps/histpoint	1.975		146
/gate/source/VS_beta/gps/histpoint	2		128
/gate/source/VS_beta/gps/histpoint	2.025		110
/gate/source/VS_beta/gps/histpoint	2.05		93
/gate/source/VS_beta/gps/histpoint	2.075		77
/gate/source/VS_beta/gps/histpoint	2.1		61
/gate/source/VS_beta/gps/histpoint	2.125		47
/gate/source/VS_beta/gps/histpoint	2.15		34
/gate/source/VS_beta/gps/histpoint	2.175		23
/gate/source/VS_beta/gps/histpoint	2.2		14
/gate/source/VS_beta/gps/histpoint	2.225		7
/gate/source/VS_beta/gps/histpoint	2.25		2
/gate/source/VS_beta/gps/histpoint	2.275		0
/gate/source/VS_beta/gps/arbint Lin

# #############################
# # Positron decay branch
# #############################

# /gate/source/addSource VS_positron
# /gate/source/VS_positron/gps/type Volume
# /gate/source/VS_positron/gps/shape Cylinder
# /gate/source/VS_positron/gps/radius 2. cm
# /gate/source/VS_positron/gps/halfz 1.0 cm
# /gate/source/VS_positron/gps/centre 0. 0. 0. cm
# /gate/source/VS_positron/setActivity 300. Bq
# /gate/source/VS_positron/gps/angtype iso
